// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
    schema: 'prisma/schema.prisma',
    migrations: {
        path: 'prisma/migrations',
        seed: `bun prisma/seed.ts`,
    },
    datasource: {
        // `env('DATABASE_URL')` resolves eagerly at import time and throws
        // (PrismaConfigEnvError) when unset — which breaks pure codegen like
        // `prisma generate` on a fresh clone with no .env. Resolve it ourselves
        // with the docker-compose default fallback so `generate` (and
        // migrate/seed against a running `bun run docker:up`) work with zero
        // env. Production always sets DATABASE_URL, so the fallback never runs
        // there. POSTGRES_PORT is the host port docker-compose.dev.yml
        // publishes it on (`bun run setup` moves it off 5432 when taken).
        //
        // The database name is LOCAL_DATABASE_NAME from app/config.ts, written
        // here as a literal because the production image ships this file
        // without app/ (`prisma migrate deploy` would fail to import it).
        // `bun run setup` rewrites it; tools/identity.test.ts checks it.
        url:
            process.env.DATABASE_URL ??
            `postgresql://postgres:postgres@localhost:${process.env.POSTGRES_PORT || 5432}/iridium`,
    },
});
