// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
    schema: 'prisma/schema.prisma',
    migrations: {
        path: 'prisma/migrations',
        seed: `bun prisma/seed.ts`,
    },
    datasource: {
        // `env('DATABASE_URL')` resolves eagerly at import time and throws
        // (PrismaConfigEnvError) when unset — which breaks pure codegen like
        // `prisma generate` on a fresh clone with no .env. Resolve it ourselves
        // with the docker-compose default fallback so `generate` (and
        // migrate/seed against a running `bun run docker:up`) work with zero
        // env. Production always sets DATABASE_URL, so the fallback never runs
        // there.
        url:
            process.env.DATABASE_URL ??
            'postgresql://postgres:postgres@localhost:5432/iridium',
    },
});
