export enum Paths {
    API = '/api',
    AUTHENTICATE = '/authenticate',
    BETTER_AUTH = '/auth/*',
    CHAT = '/chat',
    DASHBOARD = '/dashboard',
    DESIGN = '/design',
    EMAIL = '/email',
    FILE_BROWSER = '/files',
    FORMS = '/forms',
    HEALTH = '/health',
    HOME = '/',
    INTEREST = '/interest',
    PORTAL = '/portal',
    PROFILE = '/profile',
    PROFILE_EDIT = '/edit',
    SIGN_IN = '/sign-in',
    SIGN_OUT = '/sign-out',
    SUCCESS = '/success',
    THREAD = ':threadId',
    THREADS = 'threads',
    WEBHOOKS = '/webhooks',
}
